services:
  hadoop-master:
    image: yassern1/hadoop-spark-jupyter:1.0.3
    container_name: hadoop-master
    hostname: hadoop-master
    tty: true
    stdin_open: true
    networks:
      - hadoop
    volumes:
      - ${LOCAL_PROJECT_PATH}:/shared_volume
    ports:
      - "9870:9870"
      - "8088:8088"
      - "7077:7077"
      - "19888:19888"
      - "8080:8080"
      - "9000:9000"

  hadoop-slave1:
    image: yassern1/hadoop-spark-jupyter:1.0.3
    container_name: hadoop-slave1
    hostname: hadoop-slave1
    tty: true
    stdin_open: true
    networks:
      - hadoop
    ports:
      - "8040:8042"

  hadoop-slave2:
    image: yassern1/hadoop-spark-jupyter:1.0.3
    container_name: hadoop-slave2
    hostname: hadoop-slave2
    tty: true
    stdin_open: true
    networks:
      - hadoop
    ports:
      - "8041:8042"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    hostname: kafka-ui
    networks:
      - hadoop
    ports:
      - 8081:8080
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=hadoop-master:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=hadoop-master:2181

networks:
  hadoop:
    driver: bridge